# Generated by Django 5.0.3 on 2024-07-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_media',
            field=models.URLField(blank=True, null=True),
        ),
    ]
